version: '3'

services:
  flyway:
    image: boxfuse/flyway:5-alpine
    command: -url=jdbc:postgresql://postgres:5432/pi -schemas=public -user=fatec -password=fatec -connectRetries=10 migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    domainname: postgres
    build: ./migration
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: pi

  app:
    build: ./app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5001:5000
    environment:
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: pi

  postgres:
    image: postgres
    container_name: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: pi
    depends_on: 
      - flyway

  sonarqube:
    image: sonarqube
    container_name: sonarqubeR4u
    ports:
    - 9000:9000
