version: '3'

services:
  app:
    build: ./app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5001:5000
    environment:
      POSTGRES_USER: fatec
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: pi
      
  sonarqube:
    image: sonarqube
    container_name: sonarqubeR4u
    ports:
    - 9000:9000
