# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: r4uorg-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install psycopg2-binary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run docker
      run: |
        docker-compose up

    - name: Test with pytest
      run: |
        cd app
        pytest function_test.py
